-- NetZone Phase 3: Supabase setup
-- Run this in Supabase SQL Editor.

create table if not exists public.print_orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text not null,
  phone text not null,
  copies integer not null check (copies between 1 and 500),
  print_type text not null check (print_type in ('bw','color')),
  notes text,
  original_filename text not null,
  storage_path text not null,
  status text not null default 'pending'
    check (status in ('pending','printing','ready','completed','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists print_orders_status_idx
  on public.print_orders(status);

create index if not exists print_orders_created_at_idx
  on public.print_orders(created_at desc);

-- Create a private Storage bucket named: print-orders
-- Recommended: keep it PRIVATE. Files should be accessed through
-- authenticated/admin operations or short-lived signed URLs.
