-- NetZone Phase 6 — Production Supabase hardening
-- Run after the Phase 3 schema (or use this as the consolidated schema).

create table if not exists public.print_orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text not null,
  phone text not null,
  copies integer not null check (copies between 1 and 500),
  print_type text not null check (print_type in ('bw','color')),
  notes text,
  original_filename text not null,
  storage_path text not null,
  status text not null default 'pending'
    check (status in ('pending','printing','ready','completed','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists print_orders_status_idx
  on public.print_orders(status);
create index if not exists print_orders_created_at_idx
  on public.print_orders(created_at desc);

alter table public.print_orders enable row level security;

-- Do NOT add anon/authenticated SELECT/INSERT policies here.
-- The current Node server performs customer/admin operations server-side
-- with the Supabase secret key. This prevents the browser from directly
-- reading customer orders.

-- Storage:
-- Create a PRIVATE bucket named `print-orders`.
-- No public read policy is required for the current architecture.
-- The server creates short-lived signed URLs for admin document access.
